

name: Update Unity UPM semantic versioning

on: 
  workflow_run:
    workflows: ["Update Unity project semantic versioning"]
    branches: [main]
    types:
      - completed

jobs:
  create:
    name: Update semver in UPM package & project settings
    runs-on: ubuntu-latest
    
    steps:
      # You must ALWAYS checkout your repo so that actions in the workflow can use it.
      - name: Checkout "UPM" branch
        uses: actions/checkout@v2
        with:
          ref: upm

      - name: Find UPM package.json & increment its version number
        uses: AlexHolderDeveloper/UnityUPMSemver@v0.0.1 # Change vX.X.X to whatever tag is newer in the AlexHolderDeveloper/UnityUPMSemver repository.
        id: semver-update-upm
        with:
          semver-update-type: 'patch' # Change this string to any suitable string mentioned in the Inputs section of this action's readme to suit your needs.
          upm-package-directory: '/'

      # Validate that the number has been incremented correctly.
      - name: Get the new semver number
        run: echo "The new semver number for this Unity project is ${{ steps.semver-update-upm.outputs.semver-number }}"

      # Commit & push the updated semver number back into the repo. Yes, you have to fetch & pull in your local workstation after this step is done.
      - name: Push changed files back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated semver via automated action."
          commit_options: '--no-verify --signoff'
          branch: upm
      
            # You must ALWAYS checkout your repo so that actions in the workflow can use it.
      - name: Checkout "master" branch
        uses: actions/checkout@v2


      - name: Find UPM package.json & increment its version number
        uses: AlexHolderDeveloper/UnityUPMSemver@v0.0.1 # Change vX.X.X to whatever tag is newer in the AlexHolderDeveloper/UnityUPMSemver repository.
        id: semver-update-master
        with:
          semver-update-type: 'patch' # Change this string to any suitable string mentioned in the Inputs section of this action's readme to suit your needs.
          upm-package-directory: '/Assets/BigfootDS/BigfootUnityUtilities/'

      # Validate that the number has been incremented correctly.
      - name: Get the new semver number
        run: echo "The new semver number for this Unity project is ${{ steps.semver-update-master.outputs.semver-number }}"

      # Commit & push the updated semver number back into the repo. Yes, you have to fetch & pull in your local workstation after this step is done.
      - name: Push changed files back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated semver via automated action."
          commit_options: '--no-verify --signoff'
          branch: master
